COPTS = -g -O2 -Wall

# GLUTDEFS = -DUSE_FREEGLUT
# GLUTLIBS = -L/usr/X11R6/lib64 -lfreeglut-1.3 -lglib -lXxf86vm

GLUTDIR = /usr/local/src/grap/glut-3.7.32
GLUTDEFS = -I${GLUTDIR}/include
GLUTLIBS = -L${GLUTDIR}/lib/glut -lglut -L/usr/X11R6/lib -lX11 -lXmu

DEFS = ${GLUTDEFS}
CFLAGS = ${COPTS} ${DEFS}
LIBS = -lpthread

IMGLIB = /u/src/grap/libimg
IMAGELIB = /u/src/grap/libimage
IMGLIBS = -L${IMGLIB} -limg -L${IMAGELIB} -limage -ltiff -ljpeg -lm
IMGINCS = -I${IMGLIB} 
GLLIBS  = ${GLUTLIBS} -lGL -lGLU -lm
GLINCS  = -I/usr/X11R6/include

PROGS = bplay32 img2bmv32 bpio32 onethread32

all: ${PROGS}

clean:
	rm -f ${PROGS} *.o

bplay32:	bplay32.o bpio32.o 
	${CC} -o $@ bplay32.o bpio32.o ${GLLIBS} ${LIBS}

bpio32.o: bpio.c bpio.h
	${CC} -c -o $@ bpio.c ${COPTS} -O0 ${DEFS} ${GLINCS}

bplay32.o: bplay.c bpio.h bpmovie.h
	${CC} -o $@ -c bplay.c ${COPTS} ${DEFS} ${GLINCS}

img2bmv32: img2bmv.c bpmovie.h ${IMGLIB}/libimg.a ${IMAGELIB}/libimage.a 
	${CC} -c -o $@.o ${CFLAGS} ${IMGINCS} img2bmv.c
	${CC} -o $@ $@.o ${COPTS} ${IMGLIBS}

txspeed: txspeed.c
	${CC} -o $@ $@.c -g -O ${GLINCS} ${GLLIBS}

bpiotest32.o: bpiotest.c
	${CC} -c -o $@ ${CFLAGS} bpiotest.c

bpio32:	bpiotest32.o bpio32.o
	${CC} -o $@ bpiotest32.o bpio32.o ${COPTS} ${LIBS}

bpio32.o bpiotest32.o:	bpio.h

onethread32: onethread.c
	${CC} -o $@ onethread.c ${COPTS}
