Summary: SAGE Scalable Adaptive Graphics Environment
Name: sage-graphics
Version: 3.1
Release: 3
Source0: %{name}-%{version}.tar.gz
License: BSD
Group: Graphics/Streaming
%description
SAGE is a graphics streaming architecture for supporting collaborative scientific visualization environments with potentially hundreds of megapixels of contiguous display resolution. In collaborative scientific visualization, it is crucial to share high-resolution imagery as well as high-definition video among groups of collaborators at local or remote sites. The network-centered architecture of SAGE allows collaborators to simultaneously run various applications (such as 3D rendering, remote desktop, video streams and 2D maps) on local or remote clusters, and share them by streaming the pixels of each application over ultra-high-speed networks to large tiled displays. SAGE streaming architecture is designed so that the output of arbitrary M by N pixel rendering cluster nodes can be streamed to X by Y pixel display screens, allowing user-definable layouts on the display. The dynamic pixel routing capability of SAGE lets users freely move and resize each application's imagery over tiled displays in run-time, tightly synchronizing the multiple visualization streams to form a single stream.
%prep
%setup
%build
./configure
make -j 4
%install
make install
%clean
%post
ldconfig
%files
%defattr(-,root,root)
/etc/profile.d/sage.csh
/etc/profile.d/sage.sh
/etc/ld.so.conf.d/sage.conf
/usr/local/sage/bin/fsManager
/usr/local/sage/bin/sageDisplayManager
/usr/local/sage/bin/appLauncher/appLauncher.py
/usr/local/sage/bin/appLauncher/GO
/usr/local/sage/bin/appLauncher/myprint.py
/usr/local/sage/bin/appLauncher/request.py
/usr/local/sage/bin/appLauncher/data.py
/usr/local/sage/bin/appLauncher/subprocess.py
/usr/local/sage/bin/appLauncher/KILL_LAUNCHER.py
/usr/local/sage/bin/appLauncher/sage.conf
/usr/local/sage/bin/appLauncher/README
/usr/local/sage/bin/appLauncher/admin.py
/usr/local/sage/include/appInstance.h
/usr/local/sage/include/appleMultiContext.h
/usr/local/sage/include/audioConverter.h
/usr/local/sage/include/audioFileReader.h
/usr/local/sage/include/audioFileWriter.h
/usr/local/sage/include/audioFormatManager.h
/usr/local/sage/include/displayContext.h
/usr/local/sage/include/displayInstance.h
/usr/local/sage/include/envInterface.h
/usr/local/sage/include/fsClient.h
/usr/local/sage/include/fsCore.h
/usr/local/sage/include/fsManager.h
/usr/local/sage/include/fsServer.h
/usr/local/sage/include/messageInterface.h
/usr/local/sage/include/misc.h
/usr/local/sage/include/overlayApp.h
/usr/local/sage/include/overlayPointer.h
/usr/local/sage/include/pixelDownloader.h
/usr/local/sage/include/sage.h
/usr/local/sage/include/sageAppAudio.h
/usr/local/sage/include/sageAudio.h
/usr/local/sage/include/sageAudioBridge.h
/usr/local/sage/include/sageAudioCircBuf.h
/usr/local/sage/include/sageAudioManager.h
/usr/local/sage/include/sageAudioModule.h
/usr/local/sage/include/sageAudioReceiver.h
/usr/local/sage/include/sageAudioSync.h
/usr/local/sage/include/sageBase.h
/usr/local/sage/include/sageBlock.h
/usr/local/sage/include/sageBlockPartition.h
/usr/local/sage/include/sageBlockPool.h
/usr/local/sage/include/sageBlockQueue.h
/usr/local/sage/include/sageBridge.h
/usr/local/sage/include/sageBuf.h
/usr/local/sage/include/sageConfig.h
/usr/local/sage/include/sageDisplay.h
/usr/local/sage/include/sageDisplayManager.h
/usr/local/sage/include/sageDoubleBuf.h
/usr/local/sage/include/sageDraw.h
/usr/local/sage/include/sageDrawObject.h
/usr/local/sage/include/sageEvent.h
/usr/local/sage/include/sageFrame.h
/usr/local/sage/include/sagePixelType.h
/usr/local/sage/include/sageReceiver.h
/usr/local/sage/include/sageRect.h
/usr/local/sage/include/sageSharedData.h
/usr/local/sage/include/sageStreamer.h
/usr/local/sage/include/sageSync.h
/usr/local/sage/include/sageTcpModule.h
/usr/local/sage/include/sageUdpModule.h
/usr/local/sage/include/sageVirtualDesktop.h
/usr/local/sage/include/sail.h
/usr/local/sage/include/sdlSingleContext.h
/usr/local/sage/include/streamInfo.h
/usr/local/sage/include/streamProtocol.h
/usr/local/sage/include/suil.h
/usr/local/sage/include/tileConfig.h
/usr/local/sage/include/wavConverter.h
/usr/local/sage/lib64/libquanta.so
/usr/local/sage/lib64/libsail.so
/usr/local/sage/bin/VNCViewer.conf
/usr/local/sage/bin/atlantis.conf
/usr/local/sage/bin/bitplayer.conf
/usr/local/sage/bin/fsManager.conf
/usr/local/sage/bin/imageviewer.conf
/usr/local/sage/bin/render.conf
/usr/local/sage/bin/sage
/usr/local/sage/bin/sageBridge.conf
/usr/local/sage/bin/sageLauncher.py
/usr/local/sage/bin/stdtile-1.conf
/usr/local/sage/bin/stdtile-2.conf
/usr/local/sage/bin/stdtile-20.conf
/usr/local/sage/bin/stdtile.conf
/usr/local/sage/bin/subprocess.py
/usr/local/sage/bin/yuv.frag
/usr/local/sage/bin/yuv.vert
/usr/local/sage/bin/VNCViewer
/usr/local/sage/bin/atlantis
/usr/local/sage/bin/bplay-noglut
/usr/local/sage/bin/bridgeConsole
/usr/local/sage/bin/checker
/usr/local/sage/bin/fsConsole
/usr/local/sage/bin/imageviewer
/usr/local/sage/bin/render
/usr/local/sage/bin/sageBridge
/usr/local/sage/bin/uiConsole
